version: "3.0"
services:
  prod-user-service:
    image: ${ECR_REGISTRY}/${IMAGE_NAME}:${TAG}
    ports:
      - 9100:9100
      - 9101:9101
    environment:
      - GRPC_PORT=9100
      - HTTP_PORT=9101
      - DB_HOST=prod-postgre
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=user-service
      - JWT_SECRET=secret
      - JWT_EXPIRED_TIME=6h
      - REDIS_SERVER=redis_prod:6379
    networks:
      - grpc_network
networks:
  grpc_network:
    external: true