version: "3.0"
services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - APP_PORT=:9000
      - DB_HOST=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=user-service
    depends_on:
      database:
        condition: service_healthy
    networks:
      - user-net
  database:
    image: postgres:9.6
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=user-service
    ports:
      - 5433:5432
    expose:
      - 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - user-net
volumes:
  db:
    driver: local
networks:
  user-net:
    driver: bridge